organization: Tesk-challange
extends:
  - recommended
apis:
  customerAPI@v1:
    root: ./openapi/openapi.yaml
    rules:
      no-ambiguous-paths: error

    labels:
      - external
    features.openapi:
      htmlTemplate: ./docs/index.html
      theme:
        colors:
          primary:
            main: "#32329f"
      hideLogo: true

features.openapi:
  schemaExpansionLevel: 2