openapi: 3.0.2
info:
  version: 1.0.0
  title: Task-Challange
  termsOfService: ''
  contact:
    email: mghossain.42@gmail.com
    url: 'http://localhost'
  license:
    name: Not Licensed
    url: '/'
  x-logo:
    url: 'https://redocly.github.io/openapi-template/logo.png'
  description: >
    This is Web App that utilizes Laravel/PostgreSQL as backend and ReactJs as frontend.

    # Introduction

    Task-challange is a Web App that manages Customers and verify
     their phone numbers using a number valiation API.

    [Laravel](https://laravel.com/) is used to build the RESTful APIs and serves as the back-end.
    This solution contains two seperate laravel apps: CustomerAPI and NumverifyAPI
    <br>CustomerAPI micros-service contains APIs responsible for Add, Update, Delete and Get all.
    <br>[CustomerAPI Github-repo](https://github.com/mghossain/task-challange.git)
    <br>NumverifyAPI app conatins 1 micro-service for verifying the number provided by the customer.
    <br>[NumverifyAPI Github-repo](https://github.com/mghossain/NumberValidation.git)


    [PostgreSQL](https://www.postgresql.org/) is used as the database management system.


    [Reactjs](https://reactjs.org/is) is used as the frontend library for demonstrating the API's functionalities.
    <br>The front-end also demonstrates the use of [tailwind.css](https://tailwindcss.com/) a CSS framework.
    <br>[Reactjs Github-repo](https://github.com/mghossain/frontEnd-taskChallenge.git)


    All of the solution is packed into a [Docker](https://docs.docker.com/) image.
    <br>Instructions will follow on how to configure and run the container.


    It also demonstrates features of the
    [numverifyAPI](https://apilayer.com/marketplace/number_verification-api) API.


    -Parts that should be improved:
    <br>NumverifyAPI app should use a light-weight framework(Laravel's Lumen)
    <br>The front-end design and visuals should be improved.
    <br>-Parts that are efficient:
    <br>The app is containarized so it can be deployed on any environment.
    <br> The APIs utilize a workflow convention of validate, persist, return.


    # Task-challange Specification

    The goal of The Task-Challange is to build, and render
    an interface to managing customers' REST APIs .


    This documentation contains references to all the APIs used, testing
    these APIs as well as the functionalities and behaivior.

tags:
  - name: NumverifyAPI
    description: Example NumverifyAPI operations
  - name: CustomerAPI
    description: Operations about CustomerAPI
  - name: Docker-Depolyment
    description: Instruction on running the docker container
servers:
  - url: ''

paths:
  /{customers}:
    $ref: './paths/users@{username}.yaml'
  /numvalidate:
    $ref: ./paths/echo.yaml
  /docker:
    $ref: ./paths/docker.yaml
components:
  securitySchemes:
    main_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: 'http://example.com/api/oauth/dialog'
          scopes:
            'show:customers': show all customers
            'write:user': modify or remove customer
            'add:customer': add a customer
    api_key:
      type: apiKey
      in: header
      name: api_key
    #basic_auth:
      #type: http
      #scheme: basic
